apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: youtube-frontend-pdb
  namespace: default
  labels:
    app.kubernetes.io/name: youtube-frontend
    app.kubernetes.io/instance: youtube-frontend-prod
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: dvn-workshop
    app.kubernetes.io/managed-by: kubectl
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: youtube-frontend
      app.kubernetes.io/instance: youtube-frontend-prod
