apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend
  - frontend

commonLabels:
  app.kubernetes.io/part-of: dvn-workshop
  app.kubernetes.io/managed-by: kustomize

namespace: default
